### ISSUE TITLE
UI Budgets

### ISSUE THREAD

**Issue by yicheng-Pan** [miw-upm/betca-tpv#10]

**Comment by miw-upm** [comment]
Error de workflow en: de70d552 yicheng <yicheng.pan@alumnos.upm.es> on 03/03/2021 at 20:23
Error de workflow en: 76fb87e3 yicheng <yicheng.pan@alumnos.upm.es> on 03/03/2021 at 20:36
Error de workflow en: 9ca84385 yicheng <yicheng.pan@alumnos.upm.es> on 03/03/2021 at 20:39

**Comment by miw-upm** [comment]
Error de workflow en: c8be3fdc yicheng <yicheng.pan@alumnos.upm.es> on 03/03/2021 at 21:25
