### ISSUE TITLE
Send Email to Customer

### ISSUE THREAD

**Issue by wzwzDev** [miw-upm/betca-tpv#185]
- [x] Update Ticket Service
- [x] Update MailService

**Comment by miw-upm** [comment]
Buenas tardes, estoy buscando el issue 222, donde se ha realizado un flujo de trabajo incorrecto, y no existe el issue!

**Comment by wzwzDev** [comment]
![betca-tpv-core – Repository Diff_ MailService java 3_27_2022 6_20_30 PM](https://user-images.githubusercontent.com/46055260/160292976-19c15546-6f03-4ba8-85b4-c779d4aa6bf9.png)

Buenas tardes, no entiendo que ha pasado. Te envio captura de pantalla del issue que pushed.

commit 2afcbc0a098092f28d71274b2cc254c58a8db4c8

**Comment by miw-upm** [comment]
Me refiero que los issue deben estar antes en github. Intenta seguir este enlace: https://github.com/miw-upm/betca-tpv/issues/222

**Comment by miw-upm** [comment]
No has creado antes el issue en el proyecto de gestión!!!

**Comment by wzwzDev** [comment]
Sí lo he creado, no entiendo porque no sale
