### ISSUE TITLE
Interfaz para VAT Management

### ISSUE THREAD

**Issue by SusanaGonzalezPereira** [miw-upm/betca-tpv#219]
Crear una interfaz de usuario con los mocks necesarios para cubrir el caso de uso

Gestionar el Tax trimestral: A partir de un trimestre introducido por el usuario, el sistema devolverá el calculo del Tax para ese trimestre asociado a cada uno de los tipos de Tax. El año se divide en cuatro trimestres. Dado un trimestre se debe calcular el baseTax y valueTax, de todos los artículos sumados, de todos los tickets creados en el trimestre de análisis, agrupados según los tres tipos de Tax: SUPER_REDUCED("4"), REDUCED("10"), GENERAL("21").

 Se solicita un trimestre de un año, y devuelve: año, trimestre, baseTax(4):?, valueTax(4):?, baseTax(10):?, valueTax(10):?, baseTax(21):?, valueTax(21):?, totalBaseTax y totalValueTax.

**Comment by SusanaGonzalezPereira** [comment]
Primer commit: https://github.com/miw-upm/betca-tpv-angular/commit/9d2acc88e63d371ed2f9e8d96e8f0ab82e74cbbd 
- Modificadas los ficheros comunes y creado el esqueleto del componente.
- Actualizado tiempo.
![Image](https://user-images.githubusercontent.com/25640718/220098634-158db12f-bd16-4879-bc0e-0457b56c56ed.png)

**Comment by SusanaGonzalezPereira** [comment]
Segundo commit: https://github.com/miw-upm/betca-tpv-angular/commit/34b755bea4b2488c450f1990a167ecf12a4a1b9d
- añadidas las vistas necesarias para la US.
- Tiempo total utilizado según wakatime:

![Image](https://user-images.githubusercontent.com/25640718/220133464-39e0bfcb-9b5e-48f2-ac4a-594d9c57b71c.png)

**Comment by miw-upm** [comment]
Este commit: f79eb838 susana <susanagp96@gmail.com> on 20/02/2023 at 12:53, no es necesario ya que el issue #219 ya estaba actualizado respecto a develop

**Comment by miw-upm** [comment]
Los warning no quitan puntos, solo son avisos
