### ISSUE TITLE
Desarrollar la función para poder eliminar un presupuesto (budget) en el betca-tpv-core

### ISSUE THREAD

**Issue by taras-podolchak** [miw-upm/betca-tpv#289]

**Comment by miw-upm** [comment]
Hola, fusionaste con develop estando roto y luego lo dejaste roto

**Comment by taras-podolchak** [comment]
Hola, Si. Pero pasando los test en local no había errores. El error mostraba solamente en el Actions de GitHub por  la culpa de un test (que en local funcionaba perfectamente).

Subiendo a la rama develop no había ningún aviso de que algo esta roto.
