### ISSUE TITLE
UI Reviews

### ISSUE THREAD

**Issue by MRxRafi** [miw-upm/betca-tpv#3]
Link to description: https://github.com/miw-upm/betca-tpv/wiki#story-customer-reviews

<details>
<summary>UI Wireframe</summary>
<br>
<img src="https://user-images.githubusercontent.com/38105703/108905116-9e7d2f00-761f-11eb-84cc-b2a08d6564cc.PNG"/>
<img src="https://user-images.githubusercontent.com/38105703/108905127-a210b600-761f-11eb-8c12-9bca16ea4ffd.PNG" />
</details>

**Comment by miw-upm** [comment]
Antes de incorporar los cambios a develop, debes acordarte incorporar los cambios de develop a tu rama, si develop a evolucionado. 41ae695c MRxRafi <rafadriveclase@gmail.com> on 02/03/2021 at 18:41
