### ISSUE TITLE
UI for Salespeople

### ISSUE THREAD

**Issue by Martahc** [miw-upm/betca-tpv#386]

**Comment by miw-upm** [comment]
Has tenido dos errores importantes, el primero es que seguramente has partido de un develop local antiguo, porque no has hecho fetch justo antes de empezar a trabajar. El segundo es que antes de incorporar los cambios a develop, debes meter los cambios de develop en tu rama , cuando develop ha evolucionado respecto del inicio del issue. Vigila esto ya que ahora estos despistes pueden ser muy conflictivos
