### ISSUE TITLE
Customer Points Domain Model

### ISSUE THREAD

**Issue by ybrooks08** [miw-upm/betca-tpv#39]
Core Code:

Lines of codes number in this issue:
CustomerPoint - model - 27 lines of code
CustomerPointEntity - entity - 18 lines of code

-----Total lines of code: 45 -----

**Comment by miw-upm** [comment]
Este commit es innecesario: 4cd506da ybrooks08 <yosbel88@gmail.com> on 06/03/2022 at 16:48
