### ISSUE TITLE
Creation and reading of Vouchers

### ISSUE THREAD

**Issue by gnavio** [miw-upm/betca-tpv#403]
Perform creation and reading. Deletion or changing its content should not be allowed.

**Comment by miw-upm** [comment]
El flujo de este commit es erroneo: 606f322f Guillermo Navío <100093310+gnavio@users.noreply.github.com> on 02/03/2024 at 21:27

**Comment by miw-upm** [comment]
Este commit es erroneo: 75cf95f8 Guillermo Navío <100093310+gnavio@users.noreply.github.com> on 03/03/2024 at 11:33
