### ISSUE TITLE
Create Customer Points

### ISSUE THREAD

**Issue by ybrooks08** [miw-upm/betca-tpv#41]
Total lines of code: 328
Time: 4.5 hours.

**Comment by ybrooks08** [comment]
Cosumed: 2 hours.
Lines of code on commit: Added Customer Points Dto, Service and others. #41

- CustomerPointsPersistence.java -------------- 10 lines of code
- CustomerPointsService.java ------------------  22 lines of code
- CustomerPointsDto.java ----------------------  28 lines of code
- CustomerPointsResource.java  ----------------  30 lines of code
- CustomerPointsReactive.java   ----------------    9 lines of code
- CustomerPointsEntity.java      ----------------- 18 lines of code
- CustomerPointsPersistenceMongodb.java ---  26 lines of code
- CustomerPointsResourceIT.java --------------  30 lines of code

-------------  Total lines: 173 lines of code ---------

**Comment by ybrooks08** [comment]
Consumed: 2.5 hours
Lines of code on commit:  [Added create and test. #41](https://github.com/miw-upm/betca-tpv-core/commit/f2a5ef6cbec5f172675cdcafa821385529ed4fba)
- CustomerPointsPersistence.java ------------------ 1 line of code
- CustomerPointsService.java ----------------------  5 lines of code
- CustomerPointsResource.java---------------------  8 lines of code
- CustomerPointsPersistenceMongodb.java -------  6 lines of code
- CustomerPointsTest.java-------------------------  34 lines of code
- CustomerPointsServiceIT.java -------------------- 58 lines of code
- CustomerPointsPersistenceMongodbIT.java----  43 lines of code  

------------- Total lines of code: 155  --------------------------------

**Comment by miw-upm** [comment]
Hola, el issue #41 tiene 5 commits, pero la rama pierde la continuidad temporal. Ya te avisé de este error. Si no quieres ir perdiendo puntos poco a poco, te recomiendo que aprendas como hacerlo bien. Un saludo
