### ISSUE TITLE
Spring Online Orders make order progress Admin

### ISSUE THREAD

**Issue by JorgeDSDP** [miw-upm/betca-tpv#437]
- Create a findAll endpoint for Online Orders
- Create an endpoint for updating the OnlineOrderState of an order (which needs to update the ticket items state)

**Comment by miw-upm** [comment]
Este commit es innecesario: 4ee1f6e4 JorgeDSDP <jorge.dasilva@alumni.mondragon.edu> on 06/03/2024 at 21:42
