### ISSUE TITLE
Proccess Cash movements

### ISSUE THREAD

**Issue by AlvaroRGZ** [miw-upm/betca-tpv#532]

**Comment by AlvaroRGZ** [comment]
Mientras pusheaba el codigo a github, la consola del intelliJ ha crasheado parece que dejando el push a medias. He tenmido que reiniciar todo y cuando abrí el commit estaba malformado. por lo que me daba conflicto al intentar solventar el error de integracion desde la rama issue#532, es por ello que he commiteado en develop. Esto lo he hecho como ultimo recurso en vista de que no queria molestar al resto. En toda la practica he seguido un uso impecable del workflow menos esta bez que ha crasheado el IntelliJ

**Comment by miw-upm** [comment]
Este test da error en local y lo he comentado:  void testFindCashierClosuresByMonth()
