### ISSUE TITLE
Credit Line UI

### ISSUE THREAD

**Issue by raul99calderon** [miw-upm/betca-tpv#7]
- Create CRUD UI for Credit Lines
- Extend UI of tickets pay process

**Comment by miw-upm** [comment]
Hola, la rama creada debe tener continuidad en el tiempo, y en tu caso, no existe. Cuando se realiza una aportación parcial a desarrollo, luego se debe continuar con la rama, cuando desarrollo ha evolucionado, incorporamos desarrollo a nuestra rama para poder continuar. Debes corregir esto en tu flujo de trabajo.
