### ISSUE TITLE
Added Ticket Tracking and Routes 

### ISSUE THREAD

**Issue by wzwzDev** [miw-upm/betca-tpv#8]
- [x] Component
- [x] Route

**Comment by miw-upm** [comment]
Buenas tardes, es sorprendente que se haya atrevido a quitar una etiqueta de corrección puesta por el profesor! Tomo nota de su actitud

**Comment by wzwzDev** [comment]
Buenas tardes,

Perdona. No sabia que era algo que no podia quitar, porque iba a empezarlo
de nuevo. Pensaba que al rehacerlo podia quitar la etiqueta. De verdad que
no lo he hecho con mal proposito porque no lo sabia. Te pido disculpas.

No recuerdo si lo habias avisado en clase o yo no me enteré porque me
cuesta a veces entender la informacion en español. He venido a España a
hacer el master y se me escapan muchas cosas del idioma. Ruego me disculpes.
