### ISSUE TITLE
Update Customer Points Fixes.

### ISSUE THREAD

**Issue by ybrooks08** [miw-upm/betca-tpv#92]
Update CustomerPoints fixes and update verification during reading.

**Comment by ybrooks08** [comment]
Commit: [Added update CustomerPoints fixes. #92](https://github.com/miw-upm/betca-tpv-core/commit/e3e165542d20cfa6ed2a94aaf3cd8741d2b93c5a)
Cosumed time: 2.5 hours.

Lines of code by file:

-  CustomerPointsPersistence.java -----------------------------  2 lines of code

-  CustomerPointsService.java ---------------------------------- 3 lines of code

-  CustomerPointsResource.java -------------------------------  14 lines of code

-  CustomerPointsReactive.java --------------------------------   9 lines of code

-  CustomerPointsPersistenceMongodb.java ------------------   13 lines of code

-  CustomerPointsServiceIT.java ---------------------------------  33 lines of code

-  CustomerPointsResourceIT.java ------------------------------- 10 lines of code

-  CustomerPointsPersistenceMongodbIT.java------------------  48 lines of code 

---- Total lines of code: 132 lines of code ----

**Comment by miw-upm** [comment]
Este commit es ineesario: ca922aae ybrooks08 <yosbel88@gmail.com> on 15/03/2022 at 21:51
